### PR TITLE
English revision

### PR DESCRIPTION
**Pull request by mateusmeloxyz**
Some suggestions

### CODE REVIEW

**Comment by mateusmeloxyz** [comment]
@Kansetsu I hope that you may find these changes useful!

**Comment by mateusmeloxyz** [comment]
Hey @Kansetsu , maybe you missed this PR? I think that this may be very useful for you. I hope you like it!

**Comment by Kansetsu** [comment]
> @Kansetsu I hope that you may find these changes useful!
Oh, thanks for your help @mateusgomes01! I really liked your suggestion. 😊

**Comment by mateusmeloxyz** [comment]
@Kansetsu You're wellcome!

**Pull request merged**
